// declare module 'vue-localstorage' {
//   export const $localStorage: {
//     set(key: string, value: any): void;
//     get(key: string): void;
//     remove(key: string, value: any): void;
//   };
//   export function install(Vue: any, options: any): any;
// }

// /** Declaration file generated by dts-gen */
